#!/bin/bash
# this is free software under the GPLv2
# Author: Christof Schulze, christof.schulze@gmx.net
#
URL=http://map.bb.ffm.freifunk.net/nodes.json
HOSTNAME="${COLLECTD_HOSTNAME:-localhost}"
INTERVAL="${COLLECTD_INTERVAL:-60}"

while sleep "$INTERVAL"; do
  temp=$(/usr/bin/wget -q -O - "$URL")
  totalnodes=$(echo $temp|/bin/grep -P -o "name.*?}"|/usr/bin/wc -l)
  onlinenodes=$(echo $temp|/bin/grep -P -o "name.*?}" |/bin/grep -c "online\": true")
  clients=$(echo $temp|/bin/grep -P -o "name.*?}.*?}" |/bin/grep -o -P "clientcount\": [0-9]+"|/usr/bin/awk '{sum=sum+$2} END {print sum}')
  #  echo totalnodes: $totalnodes
  #  echo onlinenodes: $onlinenodes
  #  echo clients: $clients

  echo "PUTVAL \"$HOSTNAME/exec-Freifunk_Frankfurt/gauge-Total_Nodes\" interval=$INTERVAL N:$totalnodes"
  echo "PUTVAL \"$HOSTNAME/exec-Freifunk_Frankfurt/gauge-Online_Nodes\" interval=$INTERVAL N:$onlinenodes"
  echo "PUTVAL \"$HOSTNAME/exec-Freifunk_Frankfurt/gauge-Online_Clients\" interval=$INTERVAL N:$clients"
done

